[[pages]]
path = "pages/1_Home.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "pages/2_Login_Register.py"
name = "Login / Register"
icon = "ğŸ”‘"
url_path = "login-register"

[[pages]]
path = "pages/3_Reset_Password.py"
name = "Reset Password"
icon = "ğŸ”“"
url_path = "reset-password"

[[pages]]
path = "pages/4_Patient_Information.py"
name = "Patient Information"
icon = "â„¹ï¸"
url_path = "patient-information"

[[pages]]
path = "pages/5_Disease-Specific_Tests.py"
name = "Disease-Specific Tests"
icon = "ğŸ§ª"
url_path = "disease-specific-tests"

[[pages]]
path = "pages/6_Symptom_Checker.py"
name = "Symptom Checker"
icon = "ğŸ©º"
url_path = "symptom-checker"

[[pages]]
path = "pages/7_Biomarkers.py"
name = "Biomarkers"
icon = "ğŸ”¬"
url_path = "biomarkers"

[[pages]]
path = "pages/8_Results.py"
name = "Results"
icon = "ğŸ“Š"
url_path = "results"

[[pages]]
path = "pages/9_Contact_Us.py"
name = "Contact Us"
icon = "ğŸ“§"
url_path = "contact"

[[pages]]
path = "pages/10_Privacy_Policy.py"
name = "Privacy Policy"
icon = "ğŸ›¡ï¸"
url_path = "privacy-policy"
